name: scratch_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  get: 4.6.6
  get_storage: ^2.1.1
  http: ^1.2.2
  iconsax: ^0.0.8
  intl: ^0.19.0
  logger: ^2.4.0
  google_fonts: ^6.2.1
  card_swiper: ^3.0.1
  flutter_datetime_picker_plus: ^2.2.0
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  flutter_svg: ^2.0.10+1
  geolocator: ^12.0.0
  location: ^7.0.0
  google_maps_flutter: ^2.7.1
  geocoding: ^3.0.0
  web_socket_channel: ^3.0.1
  just_audio: ^0.9.39
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
