name: scratch_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  get: 4.6.6
  get_storage: ^2.1.1
  http: ^1.2.2
  iconsax: ^0.0.8
  intl: ^0.19.0
  logger: ^2.4.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
